[package]
name = "yewduxrs"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.21.0", features = ["csr"] }
wasm-bindgen = "0.2.92"
web-sys = { version = "0.3.69", features = ["HtmlInputElement"] }
