version: '3.8'
services:
  wasm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - 8080:8080
    command: sleep infinity

networks:
  default:
    driver: overlay
